version: "3"
services:
  app:
    container_name: honeymilk_app
    build: ./docker/php
    volumes:
      - ./:/var/www
    ports:
      - 8080:8080
    tty: true

  web:
    image: nginx
    container_name: honeymilk_web
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 20080:80
    depends_on:
      - app

  db:
    container_name: honeymilk_db
    image: mysql:8.0
    command: mysqld --user=root
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 23306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=honeymilkroot
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=honeymilkpass
      - MYSQL_DATABASE=honeymilk

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - TZ=Asia/Tokyo
      - PWA_HOST=db
      - PWA_USER=admin
      - PWA_PASSWORD=honeymilkpass
    ports:
      - 4040:80

